### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by bolsoncerrado** [MoonshineSG/OctoPrint-TitleStatus#1]
Hi!

May be I'm missing something here but-.... I've installed it and I notice no difference?

Thanks!

**Comment by MoonshineSG** [comment]
Yes, it does (on my setup),
You will only notice changes on  "OFFLINE",  "CONNECTING", "PRINTING", "PAUSED",  "ERROR" and "UNKNOWN"

**Comment by bolsoncerrado** [comment]
What setup is that?

I'm on a raspi and I access it using standard browsers (firefox). Where am I supposed to see those labels?

**Comment by MoonshineSG** [comment]
I tested only on chrome (rpi as well), but I don't think firefox should be an issue. The tab title (or browser title - not sure under FF) would change.

**Comment by bolsoncerrado** [comment]
In which OS are you?

**Comment by bolsoncerrado** [comment]
On MacOS ElCapitan, neither Firefox, Chrome or Safari show up anything (printing, in this case):

![captura de pantalla 2016-02-12 a las 11 04 41](https://cloud.githubusercontent.com/assets/10992914/13003918/86d80650-d178-11e5-9c46-37b606c37fba.png)

**Comment by MoonshineSG** [comment]
I'm on mac as well... 

I see smth strange... what is "[CASE]" ?

**Comment by bolsoncerrado** [comment]
The name of my "printer"

2016-02-12 11:07 GMT+01:00 ovidiu notifications@github.com:

**Comment by bolsoncerrado** [comment]
May be if the user edits the name field and enters any information your plugin stops working?

**Comment by MoonshineSG** [comment]
on my chrome/osx i dont have square brackets.. strange... 

edit: no, I just append in front of whatever the title is...

**Comment by bolsoncerrado** [comment]
i did write them....

**Comment by bolsoncerrado** [comment]
![captura de pantalla 2016-02-12 a las 11 29 03](https://cloud.githubusercontent.com/assets/10992914/13004453/d9f37c0e-d17b-11e5-8102-42fcebbfa8af.png)

**Comment by bolsoncerrado** [comment]
Try naming your printer the same and see if your plugin still works...

**Comment by MoonshineSG** [comment]
Unfortunately I don't have access to my printer for a while... (Traveling)

**Comment by jamesarm97** [comment]
This is what i am getting in the logs:

2016-02-07 02:03:11,344 - octoprint.plugin - ERROR - Error while calling plugin title_status
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.2.8-py2.7.egg/octoprint/plugin/**init**.py", line 204, in call_plugin
    result = getattr(plugin, method)(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/octoprint_title_status/**init**.py", line 16, in on_event
    self._plugin_manager.send_plugin_message(self._identifier, self._printer.get_state_id())
AttributeError: 'Printer' object has no attribute 'get_state_id'

**Comment by MoonshineSG** [comment]
Am I right to say that you're using the "master" branch from Octoprint? Seams like the function "get_state_id" was only implemented in the "dev" and has not yet promoted to the main branch.

**Comment by jamesarm97** [comment]
Master / maintenance branch.

**Comment by MoonshineSG** [comment]
I updated the codes to handle the older versions (update manually as I have not done a release yet - i have no access to a printer so can't really test it)

**Comment by MoonshineSG** [comment]
It's now on relaese 0.0.3
@bolsoncerrado , can you test yours as well ? What branch of Octoprint are you ?

**Comment by bolsoncerrado** [comment]
I'm always on latest official versions....
will update and let you know.

**Comment by MoonshineSG** [comment]
@bolsoncerrado which branch ? devel or master ?

**Comment by bolsoncerrado** [comment]
I'm assuming master?

I tried to update on some instances of octoprint and in some worked, in
others said "couldnt complete" and in others it simply was rejected, even
after rebooting, weird.

On theones that completed, now I can notice a \* before the first [

2016-02-18 11:06 GMT+01:00 ovidiu notifications@github.com:

**Comment by bolsoncerrado** [comment]
...and a triangle when printing?

2016-02-18 11:58 GMT+01:00 Alex Tutusaus alextc@gmail.com:

**Comment by MoonshineSG** [comment]
OFFLINE - *
CONNECTING - Connecting..
PRINTING - △
PAUSED - Paused...
ERROR/CLOSED_WITH_ERROR - ERROR !!
UNKNOWN -?

**Comment by bolsoncerrado** [comment]
great then :)

**Comment by MoonshineSG** [comment]
seams like you were on the master branch of octoprint... I only tested on devel branch which has more functions. My bad! 
Hopefully now it's error free.

**Comment by bolsoncerrado** [comment]
Appartently its not updating the version number properly so it keeps asking me to update over and over...

**Comment by MoonshineSG** [comment]
Please try one more time. It should go to 0.0.4
